services:
  mongodb:
    image: mongo:7.0
    container_name: listify-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: listify
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - listify-network

volumes:
  mongodb_data:

networks:
  listify-network:
    driver: bridge 