version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: listify-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: listify
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - listify-network

networks:
  listify-network:
    driver: bridge

volumes:
  mongodb_data: 