version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: listify-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - listify-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: listify-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - listify-network

volumes:
  mongodb_data:

networks:
  listify-network:
    driver: bridge 